<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <!-- We don't need to platform-specific builds any more -->
    <AssemblyName>S7_CS_Utility</AssemblyName>
    <!-- Avalonia does require this to be null -->
    <ApplicationIcon />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.0.10" />
    <PackageReference Include="Avalonia.Desktop" Version="11.0.10" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.0.10" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.0.10" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.0.10" />
    <PackageReference Include="NModbus" Version="3.0.81" />
    <PackageReference Include="System.IO.Ports" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\\payloads\\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\S7.Net\S7.Net.csproj" />
    <ProjectReference Include="..\Core\S7.Utils\S7.Utils.csproj" />
  </ItemGroup>
</Project>
