TARGET := build/dump_mem_multisection

SRC := dump_mem_multisection.c \
    ../lib/stdlib.c \
    ../lib/print.c \
    ../lib/string.c \
    ../lib/read.c

#SRC_ASM := start.S

include ../makeinc/rules.mk
