<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>S7_CS_Utility</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NModbus" Version="3.0.81" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="payloads\\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
