<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.2.0" />
    <PackageReference Include="Moq" Version="4.20.1" />
    <PackageReference Include="FluentAssertions" Version="6.11.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\S7_Csharp_Core\S7.Infrastructure\S7.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src/S7_Csharp_Core\S7.Net\S7.Net.csproj" />
    <ProjectReference Include="..\..\src/S7_Csharp_Core\S7.Core.Commands\S7.Core.Commands.csproj" />
    <ProjectReference Include="..\..\src\S7_Csharp_Core\S7.Utils\S7.Utils.csproj" />
  </ItemGroup>

</Project>